# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RecipeProject_v2' do
  
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for RecipeProject_v2
  
    pod 'CHIPageControl', '~> 0.1.3'
    pod 'CHIPageControl/Jalapeno'
    
end
